package git

import "testing"

// TestInsecureIgnoreHostKey returns nil for any host — locks the
// default SSH callback when known_hosts isn't supplied.
func TestInsecureIgnoreHostKey(t *testing.T) {
	if err := insecureIgnoreHostKey("github.com:22", nil, nil); err != nil {
		t.Errorf("expected nil, got %v", err)
	}
}

// TestKnownHostsCallback_MaterializesFile covers the temp-file path:
// the callback constructor writes known_hosts to disk so
// golang.org/x/crypto/ssh/knownhosts can read it.
func TestKnownHostsCallback_MaterializesFile(t *testing.T) {
	// A minimal valid known_hosts file. knownhosts.New is lenient
	// about empty/comment-only files.
	data := []byte("# Generated by flate test\n")
	cb, err := knownHostsCallback(data)
	if err != nil {
		t.Fatalf("knownHostsCallback: %v", err)
	}
	if cb == nil {
		t.Error("expected non-nil callback")
	}
}
