// Package diff produces structured diffs between two sets of rendered
// Kubernetes manifests. The diff body is generated by [dyff] in its
// `--output github` mode — path-keyed (`@@ <path> @@`) with standard
// `+` / `-` value lines and `!` change-type markers, which GitHub's
// diff lexer renders natively as a colored diff block when wrapped
// in a ```diff fence. The substantive payoff over a textual unified
// diff is K8s-aware list matching: containers, env vars, and other
// named list entries are paired by their identifier (`.name`), so
// reordering a list produces an `⇆ order changed` marker instead of
// a wall of phantom value-line churn.
//
// Four output flavors are supported:
//
//   - Diff   — concatenated dyff bodies, one per resource, with a
//     per-resource `--- / +++` header banner (the default).
//   - Object — a per-resource heading followed by the dyff body.
//   - YAML   — structured YAML where each entry is a resource and its
//     dyff body.
//   - JSON   — same shape as YAML, marshaled as JSON.
//
// [dyff]: https://github.com/homeport/dyff
package diff
